"""
Training script for GCN-LSTM Encoder-Decoder model.
Air quality (PM2.5) forecasting using spatio-temporal graph neural networks.
"""

import math
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import numpy as np
import os
import time
import random
import joblib
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from models import GCNLSTMModel, GraphTransformerModel, MeteorologicalForecaster
from utils.graph import (
    build_wind_aware_adjacency_batch,
    build_dynamic_adjacency_gpu,
    build_per_timestep_adjacency_gpu,
    WIND_CATEGORIES
)

# ============================================================================
# Configuration
# ============================================================================

CONFIG = {
    # Data
    'data_path': 'data/processed/',
    'input_len': 24,        # Lookback window (hours)
    'horizon': 6,           # Prediction horizon (hours)
    
    # Model architecture
    'input_dim': 33,        # Number of input features per node
    'hidden_dim': 64,       # Hidden dimension
    'output_dim': 1,        # Output dimension (PM2.5 only)
    'num_nodes': 12,        # Number of monitoring stations
    'num_layers': 2,        # Number of Graph LSTM layers
    'num_heads': 4,         # Attention heads
    'dropout': 0.1,
    'use_direct_decoding': False,  # Direct multi-horizon decoding (no autoregression)
    'use_attention': False,        # MHA tested and removed — zero measurable effect (2026-04-14)

    # Model type switch
    # 'gcn_lstm'         — original GraphLSTM encoder-decoder (recurrent baseline)
    # 'graph_transformer'— GCN per-timestep + Transformer encoder + direct head (new)
    'model_type': 'graph_transformer',
    'num_tf_layers': 2,  # Transformer encoder layers (graph_transformer only)

    # Graph convolution type ('gcn' | 'gat')
    # 'gcn' — original GraphConvolution with normalized adjacency (default, backward-compatible)
    # 'gat' — GraphAttentionLayer: learned attention + wind-aware adjacency as additive bias
    'graph_conv': 'gat',
    'num_gat_layers': 1,   # Number of stacked GAT layers (1=1-hop, 2=2-hop neighbourhood)
    'gat_version': 'v1',  # 'v1' = standard GAT, 'v2' = GATv2 (dynamic attention)
    'use_post_temporal_gat': False,  # FAILED: Test MAE 21.022, destabilized training
    'use_temporal_attention_head': False,  # FAILED: Test MAE 21.353, full-sequence access doesn't help

    # Multi-scale temporal attention (experiment 3) — FAILED: Test MAE 20.952, mild overfitting.
    'use_multiscale_temporal': False,
    'local_window': 6,
    'n_local_layers': 1,

    # t-24 daily anchor — FAILED: gate→0.073, wider val/test gap, Test MAE 21.193
    'use_t24_residual': False,
    'initial_t24_alpha': 0.3,

    # Horizon-aware loss weighting.
    # Upweights H4-H6 in the MSE to push the model toward long-horizon accuracy.
    # Weights are normalized (mean=1) so overall loss scale is preserved.
    # Baseline per-horizon MAE: H1=10.45, H2=15.99, H3=19.81, H4=23.00, H5=25.89, H6=28.60
    # Compare against uniform baseline: Val 18.834 / Test 20.624 / RMSE 37.729.
    'horizon_loss_weights': None,

    # Oracle future meteorology experiment.
    # When enabled, the model receives the OBSERVED meteorological conditions during
    # the forecast window (hours t+1 to t+6) — primarily wind speed and direction.
    # This is oracle (perfect-foresight) information, not available in real deployment.
    # Purpose: test whether H4-H6 degradation is caused by missing future met info.
    # If this helps significantly → H4-H6 is information-limited, not architecture-limited.
    # If this barely helps → H4-H6 is intrinsically unpredictable (PM2.5 chemistry/sources).
    # Requires Z_{input_len}.npy generated by: python utils/window.py --input_len 24 --future_met
    'use_future_met': False,
    # Feature indices extracted for Z (must match window.py FUTURE_MET_INDICES):
    # temp(6), pres(7), dewp(8), rain(9), wspm(10) + wind direction one-hot (17-32) = 21 features
    'future_met_indices': [6, 7, 8, 9, 10] + list(range(17, 33)),

    # Meteorological forecaster mode (requires use_future_met=True):
    #   'oracle'    — use observed future met (ceiling, not deployable)
    #   'predicted' — pre-train MeteorologicalForecaster, use its predictions (deployable)
    #   'persistence' — repeat last-observed met for all 6 future steps (simple baseline)
    'met_forecast_mode': 'oracle',
    'met_hidden_dim': 64,        # MetForecaster hidden dim (matches PM2.5 model)
    'met_pretrain_epochs': 25,   # max pre-training epochs for MetForecaster
    'met_pretrain_patience': 5,  # early stopping patience for MetForecaster pre-training

    # Residual prediction: model outputs delta from last-observed PM2.5 (persistence baseline).
    # final_prediction = model_output + last_observed_PM2.5
    # Forces model to learn corrections to a sensible prior instead of absolute values.
    # Particularly helps longer horizons where absolute prediction is harder.
    # PM2.5 feature index in X must match config['target_feature_idx'].
    'use_persistence_residual': True,
    'target_feature_idx': 0,  # Index of PM2.5 in the feature dimension of X
    # Horizon-dependent residual weights: learned σ(logit_h) per horizon step.
    # Replaces uniform +y_last with a per-step scaled version. Initialized near 1.0.
    'use_horizon_residual_weights': False,

    # Log1p input/target transform. Applied to right-skewed features before MinMaxScaling.
    # PM2.5 (idx 0): target + input. Inverse expm1 applied after inverse_transform in metrics.
    # Pollutants (idx 1-5: PM10, SO2, NO2, CO, O3): input only, no inverse needed.
    # All have CV > 0.68; CO reaches 10,000 µg/m³. Same reasoning as PM2.5.
    'use_log_transform': True,
    'log_transform_indices': [0, 1, 2, 3, 4, 5],  # feature indices in X to apply log1p

    # Training
    'batch_size': 32,
    'learning_rate': 1e-3,
    'weight_decay': 1e-5,
    'epochs': 100,
    'patience': 15,          # Early stopping patience (back to original)
    'teacher_forcing_start': 1.0,  # Initial teacher forcing ratio
    'teacher_forcing_end': 0.0,    # Final teacher forcing ratio

    # Loss
    'loss_type': 'evt_hybrid',     # Options: 'mse' or 'evt_hybrid'
    'evt_lambda': 0.05,            # Base weight of EVT tail component (used if no schedule)
    'evt_tail_quantile': 0.90,     # Threshold quantile for extremes
    'evt_xi': 0.10,                # GPD shape parameter
    'evt_threshold': None,   
    'evt_threshold_mode': 'global',      # Populated from training targets

    # EVT Improvements: DISABLED (fixed λ=0.05 validation)
    'evt_asymmetric_penalty': False,        # Disabled for baseline comparison
    'evt_under_penalty_multiplier': 2.0,    # Not used when asymmetric_penalty=False
    'evt_use_lambda_schedule': False,       # Disabled - using fixed λ=0.05
    'evt_lambda_schedule': {
        'initial': 0.05,     # Epochs 1-25: Learn general patterns (extended warmup)
        'mid': 0.12,         # Epochs 26-50: Gentle increase in extreme focus
        'final': 0.25,       # Epochs 51+: Moderate extreme emphasis (less aggressive)
        'warmup_epochs': 25, # Extended warmup period
        'mid_epochs': 50,    # Slower transition to final
        'transition': 'smooth'  # 'smooth' for gradual, 'step' for abrupt changes
    },

    # Per-timestep dynamic adjacency.
    # When True, builds a separate A_t for each of the 24 input timesteps
    # using instantaneous wind conditions at that hour, instead of one
    # aggregated adjacency for the full window.
    # Ablation vs graph_transformer_gat_v1_residual: only adj construction changes.
    'use_per_timestep_adj': False,

    # Transport-time-weighted adjacency (experiment 2).
    # Adds a Gaussian weight peaking when the pollutant transit time d/(speed*3.6)
    # matches transport_h_ref hours, suppressing edges where transit time is a
    # poor match for the 6-hour forecast horizon.
    'use_transport_time_weight': False,
    'transport_h_ref': 3.5,
    'transport_sigma': 8.0,

    # Physics-guided Gaussian plume adjacency (experiment 4).
    # Replaces isotropic distance decay with asymmetric plume kernel:
    #   crosswind: exp(-d_cross² / (2*σ_c²))
    #   along-wind: exp(-d_along / (u_i * τ * 3.6))    [upwind → neutral fallback]
    # Physically: stations downwind and close to the plume centreline get highest weight.
    'use_physics_guided_adj': False,
    'plume_sigma_cross': 25.0,   # km, lateral (crosswind) dispersion scale
    'plume_tau': 4.0,            # hours, along-wind timescale (λ = u*τ)

    # Chinese holiday indicator feature experiment.
    # Binary feature: 1 on Spring Festival (CNY eve+day+3d after), Golden Week (Oct 1-7),
    # Labour Day (May 1-3). Encodes high-emission events the model cannot infer from met alone.
    # Requires X_{input_len}_holiday.npy generated by:
    #   python utils/window.py --add_holiday
    # Inserts at index 17 (after temporal cyclicals, before wind one-hot).
    # Wind indices auto-adjust to 18/34 when enabled.
    'use_holiday_feature': False,  # TRIED AND REJECTED 2026-04-22: test MAE +0.559, RMSE +1.626 — past-window holiday flag is redundant with temporal cyclicals; future holiday status would be needed

    # PM2.5 first-difference (delta) feature experiment.
    # When True, expects X_{input_len}_delta.npy generated by:
    #   python utils/window.py --add_pm25_delta
    # The delta is inserted at index 17 (after temporal cyclicals, before wind one-hot),
    # which shifts wind_dir_start_idx → 18 and wind_dir_end_idx → 34 (auto-applied below).
    'use_pm25_delta': False,  # TRIED AND REJECTED 2026-04-22: val MAE -0.229 but test MAE +0.306, RMSE +0.933, val/test gap widened to 2.127

    # Wind-aware adjacency
    'use_wind_adjacency': True,    # Use dynamic wind-aware adjacency
    'wind_alpha': 0.6,             # Wind influence weight (0=distance-only, 1=wind-only)
    'use_learnable_alpha_gate': True,  # Learn alpha instead of keeping wind_alpha fixed
    'use_node_embeddings': True,        # Learnable per-station identity embeddings (post-LN injection)
    'distance_sigma': 1800,        # Distance decay parameter (calibrated for Beijing ~35km mean)
    'wind_aggregation_mode': 'recent_weighted',  # 'recent_weighted' | 'last' | 'mean'
    'wind_recency_beta': 3.0,      # Recency emphasis for recent_weighted aggregation
    'wind_direction_method': 'circular',  # 'circular' | 'argmax_mean'
    'wind_normalization': 'row',   # 'row' (directed) | 'symmetric'
    'wind_calm_speed_threshold': 0.1,
    'wind_speed_idx': 10,          # Index of wind speed feature (wspm) — unchanged by delta
    'wind_dir_start_idx': 17,      # Start index of wind direction one-hot (18 when use_pm25_delta=True)
    'wind_dir_end_idx': 33,        # End index of wind direction one-hot (34 when use_pm25_delta=True)

    # Data split
    'train_ratio': 0.7,
    'val_ratio': 0.15,
    'test_ratio': 0.15,
    
    # Device
    'device': 'cuda' if torch.cuda.is_available() else 'cpu',
    
    # Paths
    'model_save_path': 'models/checkpoints/',
    'best_model_name': 'best_model.pt',

    # Checkpoint naming (for comparing different runs)
    'architecture_name': 'graph_transformer_gat_v1_residual_log1p_all_std_learnAdj',  # + learnable static adjacency

    # Learnable static adjacency: replaces precomputed Gaussian distance decay with a
    # learnable (N,N) parameter initialized from the same decay. Trained end-to-end.
    # Off-diagonal entries: sigmoid(logits). Diagonal fixed at 1.0. Row-normalized.
    'use_learnable_static_adj': True,

    # Correlation-based static adjacency (TRIED AND REJECTED 2026-04-23):
    # test MAE 19.831 vs baseline 19.813 — statistical tie. Alpha collapsed 0.33→0.21
    # due to scale mismatch (corr_norm pre-normalized vs A_dist unnormalized).
    'use_correlation_adj': False,

    # Gaussian noise augmentation (TRIED AND REJECTED 2026-04-23):
    # std=0.02 → test MAE 19.927 vs baseline 19.813. Val unchanged (18.23) but test worse.
    # Noise degraded signal without improving generalization.
    'use_noise_augmentation': False,
    'noise_std': 0.02,

    # LR schedule: cosine annealing with linear warmup (TRIED AND REJECTED 2026-04-23:
    # worse than ReduceLROnPlateau on this dataset — decays LR regardless of improvement,
    # model best at epoch 7 then stagnated. ReduceLROnPlateau holds LR until needed.)
    'use_cosine_schedule': False,
    'cosine_warmup_epochs': 5,
    'cosine_min_lr_ratio': 0.05,

    # Per-station target normalization (TRIED AND REJECTED 2026-04-22).
    # Complete statistical tie with global StdScaler — no measurable gain.
    # Global StdScaler is preferred (simpler, marginally better RMSE).
    'use_per_station_norm': False,
    'hardware_tag': 'T4',       # Options: 'integrated_gpu', 'T4', 'rtx3090', etc.
    'use_versioned_checkpoint': True,       # If True, saves as <arch>_<hardware>_best.pt

    # Resume training
    'resume': False,        # Set to True to resume from checkpoint

    # Reproducibility
    'seed': 42,
    'deterministic': False,

    # Runtime controls (useful for hyperparameter tuning)
    'save_checkpoints': True,
    'evaluate_test': True,
    'save_history': True
}


class EVTHybridLoss(nn.Module):
    """
    Hybrid loss: standard MSE + EVT tail-aware penalty.

    Penalizes errors more heavily for extreme values above the threshold.
    Uses a power-law penalty inspired by GPD to emphasize extreme value errors.

    Improvements:
    - Asymmetric penalty: under-predictions penalized more than over-predictions
    - Adaptive lambda: can be adjusted during training via set_lambda()
    """

    def __init__(self, threshold, lambda_tail=0.05, xi=0.10, eps=1e-6,
                 asymmetric_penalty=False, under_penalty_multiplier=2.0,
                 horizon_weights=None):
        super().__init__()
        # threshold can be a float (global) or a 1D array-like (per node).
        thr = torch.as_tensor(threshold, dtype=torch.float32)
        self.register_buffer("threshold", thr)
        self.lambda_tail = float(lambda_tail)
        self.xi = float(xi)
        self.eps = float(eps)
        self.asymmetric_penalty = asymmetric_penalty
        self.under_penalty_multiplier = float(under_penalty_multiplier)

        # Per-horizon loss weights: (H,) tensor, normalized so mean == 1.
        # Upweighting later horizons pushes the model to prioritize H4-H6.
        # Applied only to the base MSE; tail loss is left unweighted (lambda=0.05).
        if horizon_weights is not None:
            hw = torch.as_tensor(horizon_weights, dtype=torch.float32)
            hw = hw / hw.mean()   # normalize: preserves overall loss scale
            self.register_buffer("horizon_weights", hw)
        else:
            self.register_buffer("horizon_weights", None)

    def set_lambda(self, new_lambda):
        """Update lambda weight (for adaptive scheduling)."""
        self.lambda_tail = float(new_lambda)

    def forward(self, predictions, targets):
        # Base MSE — optionally weighted per horizon.
        # predictions/targets: (B, H, N)
        if self.horizon_weights is not None:
            H = predictions.shape[1]
            w = self.horizon_weights[:H].to(predictions.device).view(1, -1, 1)
            mse = ((predictions - targets) ** 2 * w).mean()
        else:
            mse = F.mse_loss(predictions, targets)

        # Identify extreme values (above threshold)
        thr = self.threshold.to(device=targets.device, dtype=targets.dtype)
        if thr.ndim == 0:
            thr_view = thr
        elif thr.ndim == 1:
            # Per-node thresholds; predictions/targets are (batch, horizon, nodes)
            thr_view = thr.view(1, 1, -1)
        else:
            raise ValueError(f"Unsupported threshold shape: {tuple(thr.shape)}")

        mask = targets > thr_view

        if mask.any():
            # Get predictions and targets for extreme values
            extreme_preds = predictions[mask]
            extreme_targets = targets[mask]

            # Select matching thresholds for masked elements (handles global or per-node thresholds)
            thr_selected = thr_view.expand_as(targets)[mask]
            target_excess = extreme_targets - thr_selected

            # Weighted squared error directly on predictions (keeps gradient for under-prediction)
            err = extreme_preds - extreme_targets

            # Weight increases with magnitude of excess (stabilize denominator)
            mean_excess = target_excess.mean().detach()
            excess_weight = 1.0 + self.xi * target_excess / (mean_excess + self.eps)
            excess_weight = torch.clamp(excess_weight, min=1.0)

            # Asymmetric penalty: penalize under-prediction more
            if self.asymmetric_penalty:
                under_mask = err < 0
                excess_weight = excess_weight * torch.where(
                    under_mask,
                    err.new_tensor(self.under_penalty_multiplier),
                    err.new_tensor(1.0)
                )

            tail_loss = (excess_weight * (err ** 2)).mean()
        else:
            tail_loss = torch.zeros(1, device=predictions.device, dtype=predictions.dtype)

        # Combine MSE + weighted tail penalty
        return mse + self.lambda_tail * tail_loss


def get_evt_lambda_for_epoch(epoch, schedule_config, total_epochs):
    """
    Calculate EVT lambda for current epoch based on schedule.

    Args:
        epoch: Current epoch (0-indexed)
        schedule_config: Dictionary with schedule parameters
        total_epochs: Total number of training epochs

    Returns:
        lambda value for current epoch
    """
    initial = schedule_config['initial']
    mid = schedule_config['mid']
    final = schedule_config['final']
    warmup_epochs = schedule_config.get('warmup_epochs', 20)
    mid_epochs = schedule_config.get('mid_epochs', 40)
    transition = schedule_config.get('transition', 'smooth')

    if epoch < warmup_epochs:
        # Warmup phase: stay at initial lambda
        return initial
    elif epoch < mid_epochs:
        # Transition from initial to mid
        if transition == 'smooth':
            # Linear interpolation
            progress = (epoch - warmup_epochs) / (mid_epochs - warmup_epochs)
            return initial + (mid - initial) * progress
        else:  # step
            return mid
    else:
        # Transition from mid to final
        if transition == 'smooth':
            # Linear interpolation
            progress = (epoch - mid_epochs) / max(total_epochs - mid_epochs, 1)
            progress = min(progress, 1.0)  # Cap at 1.0
            return mid + (final - mid) * progress
        else:  # step
            return final


def set_global_seed(seed, deterministic=False):
    """Set random seeds for reproducible training runs."""
    seed = int(seed)
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

    # Optional deterministic mode (slower, but more reproducible)
    if deterministic:
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False


# ============================================================================
# Data Loading
# ============================================================================

def load_data(config):
    """Load preprocessed data tensors.

    Looks for X_{input_len}.npy first (named files generated by utils/window.py
    --input_len flag). Falls back to X.npy for backward compatibility.
    """
    data_path = config['data_path']
    input_len = config['input_len']

    # Prefer named files (e.g. X_48.npy) so multiple window sizes can coexist.
    # Fall back to X.npy if the named file doesn't exist (original behaviour).
    if config.get('use_pm25_delta', False):
        suffix = '_delta'
    elif config.get('use_holiday_feature', False):
        suffix = '_holiday'
    else:
        suffix = ''
    x_named = os.path.join(data_path, f'X_{input_len}{suffix}.npy')
    y_named = os.path.join(data_path, f'Y_{input_len}{suffix}.npy')
    x_default = os.path.join(data_path, 'X.npy')
    y_default = os.path.join(data_path, 'Y.npy')

    if os.path.exists(x_named):
        X = np.load(x_named)
        Y = np.load(y_named)
        print(f"Loaded windowed data (input_len={input_len}): {x_named}")
    else:
        gen_flag = f'--input_len {input_len}' + (' --add_pm25_delta' if suffix else '')
        print(f"[Warning] {x_named} not found — falling back to X.npy. "
              f"Run: python utils/window.py {gen_flag}")
        X = np.load(x_default)
        Y = np.load(y_default)

    adj = np.load(os.path.join(data_path, 'adjacency.npy'))

    print(f"Loaded X: {X.shape}")  # (samples, input_len, num_nodes, features)
    print(f"Loaded Y: {Y.shape}")  # (samples, horizon, num_nodes)
    print(f"Loaded adjacency: {adj.shape}")  # (num_nodes, num_nodes)

    # Load future meteorological features if enabled
    Z = None
    if config.get('use_future_met', False):
        z_path = os.path.join(data_path, f'Z_{input_len}.npy')
        if not os.path.exists(z_path):
            raise FileNotFoundError(
                f"Future met tensor not found: {z_path}\n"
                f"Generate it with: python utils/window.py --input_len {input_len} --future_met"
            )
        Z = np.load(z_path)
        print(f"Loaded Z (future met): {Z.shape}")  # (samples, horizon, num_nodes, F_met)

    return X, Y, adj, Z


def extract_wind_features(X_batch, config):
    """
    Extract wind speed and direction from input batch.

    Args:
        X_batch: (batch, timesteps, num_nodes, features) tensor
        config: configuration dict

    Returns:
        wind_speeds: (batch, timesteps, num_nodes) tensor
        wind_directions: (batch, timesteps, num_nodes, num_wind_categories) tensor
    """
    wind_speed_idx = config['wind_speed_idx']
    wind_dir_start = config['wind_dir_start_idx']
    wind_dir_end = config['wind_dir_end_idx']

    # Extract wind speed (single feature)
    wind_speeds = X_batch[:, :, :, wind_speed_idx]  # (batch, timesteps, nodes)

    # Extract wind direction one-hot (multiple features)
    wind_directions = X_batch[:, :, :, wind_dir_start:wind_dir_end]  # (batch, timesteps, nodes, categories)

    return wind_speeds, wind_directions


def build_dynamic_adjacency(X_batch, config, device, alpha_override=None, sigma_override=None,
                            static_adj_override=None):
    """
    Build dynamic wind-aware adjacency matrix (or sequence) for a batch.
    Uses GPU-optimized computation when possible.

    Args:
        X_batch: (batch, timesteps, num_nodes, features) tensor
        config: configuration dict
        device: torch device
        alpha_override: learnable alpha tensor from model.get_wind_alpha() — keeps grad flow
        sigma_override: learnable sigma tensor from model.get_distance_sigma() — keeps grad flow
        static_adj_override: (N, N) learnable static adjacency from model.get_static_adj() — keeps grad flow

    Returns:
        adj_batch: (batch, num_nodes, num_nodes)            when use_per_timestep_adj=False
                   (batch, timesteps, num_nodes, num_nodes) when use_per_timestep_adj=True
    """
    # Per-timestep adjacency: build a separate A_t for each input timestep.
    # Gradients flow through alpha_override if it is a learnable tensor.
    if config.get('use_per_timestep_adj', False):
        return build_per_timestep_adjacency_gpu(
            X_batch, config,
            alpha_override=alpha_override,
            sigma_override=sigma_override,
        )

    # Use the torch implementation whenever any learnable param is provided so
    # gradients can flow from the loss back through the adjacency construction.
    if X_batch.is_cuda or alpha_override is not None or sigma_override is not None or static_adj_override is not None:
        return build_dynamic_adjacency_gpu(
            X_batch, config,
            alpha_override=alpha_override,
            sigma_override=sigma_override,
            static_adj_override=static_adj_override,
        )

    # Fallback to CPU version for non-GPU tensors
    wind_speeds, wind_directions = extract_wind_features(X_batch, config)

    # Build wind-aware adjacency
    adj_batch = build_wind_aware_adjacency_batch(
        wind_speeds=wind_speeds,
        wind_directions=wind_directions,
        wind_categories=WIND_CATEGORIES,
        alpha=config['wind_alpha'] if alpha_override is None else float(alpha_override),
        distance_sigma=config['distance_sigma'],
        aggregation_mode=config.get('wind_aggregation_mode', 'recent_weighted'),
        recency_beta=config.get('wind_recency_beta', 3.0),
        direction_method=config.get('wind_direction_method', 'circular'),
        normalization=config.get('wind_normalization', 'row'),
        calm_speed_threshold=config.get('wind_calm_speed_threshold', 0.1)
    )

    # Convert to tensor
    adj_batch = torch.FloatTensor(adj_batch).to(device)

    return adj_batch


def split_data(X, Y, config):
    """Split data into train/val/test sets (chronological split)."""
    n_samples = len(X)

    train_end = int(n_samples * config['train_ratio'])
    val_end = int(n_samples * (config['train_ratio'] + config['val_ratio']))

    X_train, Y_train = X[:train_end], Y[:train_end]
    X_val, Y_val = X[train_end:val_end], Y[train_end:val_end]
    X_test, Y_test = X[val_end:], Y[val_end:]

    print(f"\nData split:")
    print(f"  Train: {len(X_train)} samples")
    print(f"  Val:   {len(X_val)} samples")
    print(f"  Test:  {len(X_test)} samples")

    return (X_train, Y_train), (X_val, Y_val), (X_test, Y_test)


def inverse_transform_targets(arr, target_scaler):
    """
    Inverse-transform targets.
    target_scaler: single scaler (global) or list of per-station scalers.
    arr shape: (samples, horizon, nodes).
    """
    if isinstance(target_scaler, list):
        out = np.zeros_like(arr)
        for s in range(arr.shape[-1]):
            flat = arr[..., s].reshape(-1, 1)
            out[..., s] = target_scaler[s].inverse_transform(flat).reshape(arr[..., s].shape)
        return out
    orig_shape = arr.shape
    return target_scaler.inverse_transform(arr.reshape(-1, 1)).reshape(orig_shape)


def fit_scalers_on_train(X_train, Y_train, config):
    """
    Fit scalers on training data only to prevent data leakage.

    Args:
        X_train: Training input data (samples, seq_len, nodes, features)
        Y_train: Training target data (samples, horizon, nodes)
        config: Configuration dict

    Returns:
        feature_scaler: Fitted scaler for input features (excluding wind one-hot)
        target_scaler: Fitted scaler for PM2.5 targets
        already_scaled: Boolean indicating if data appears pre-scaled
    """
    # Get dimensions
    n_samples, seq_len, n_nodes, n_features = X_train.shape

    # Find wind direction feature indices (these are one-hot, don't scale)
    wind_start_idx = config.get('wind_dir_start_idx', 17)

    # Check if data appears already scaled (values mostly in 0-1 range)
    # PM2.5 (index 0) in original scale is typically 0-500+ µg/m³
    pm25_max = X_train[:, :, :, 0].max()
    pm25_min = X_train[:, :, :, 0].min()
    y_max = Y_train.max()
    y_min = Y_train.min()

    # If PM2.5 values are in 0-1 range, data is likely pre-scaled
    already_scaled = pm25_max <= 1.5 and pm25_min >= -0.5 and y_max <= 1.5 and y_min >= -0.5

    if already_scaled:
        print("  [WARNING] Data appears to be pre-scaled (values in 0-1 range).")
        print("  Skipping additional scaling to avoid double-scaling.")
        print("  For proper data leakage prevention, regenerate data:")
        print("    1. python preproccess.py")
        print("    2. cd utils && python window.py")
        return None, None, True

    # Apply log1p to skewed input features and PM2.5 target before fitting scalers.
    if config.get('use_log_transform', False):
        X_train_fit = X_train.copy()
        for idx in config.get('log_transform_indices', [0]):
            X_train_fit[:, :, :, idx] = np.log1p(X_train[:, :, :, idx])
        Y_train_fit = np.log1p(Y_train)
    else:
        X_train_fit = X_train
        Y_train_fit = Y_train

    # Flatten X for fitting: (samples * seq_len * nodes, features)
    X_flat = X_train_fit.reshape(-1, n_features)

    # Fit feature scaler on non-wind features (indices 0 to wind_start_idx)
    # This includes PM2.5 (idx 0), other pollutants, meteo, and temporal features
    feature_scaler = StandardScaler()
    feature_scaler.fit(X_flat[:, :wind_start_idx])

    # Fit target scaler(s) on Y values (PM2.5 only)
    if config.get('use_per_station_norm', False):
        target_scaler = []
        for s in range(n_nodes):
            sc = StandardScaler()
            sc.fit(Y_train_fit[:, :, s].reshape(-1, 1))
            target_scaler.append(sc)
        means = [sc.mean_[0] for sc in target_scaler]
        stds  = [sc.scale_[0] for sc in target_scaler]
        print(f"  Per-station target scalers: mean range [{min(means):.4f}, {max(means):.4f}]  "
              f"std range [{min(stds):.4f}, {max(stds):.4f}]")
    else:
        Y_flat = Y_train_fit.reshape(-1, 1)
        target_scaler = StandardScaler()
        target_scaler.fit(Y_flat)

    return feature_scaler, target_scaler, False


def scale_data(X, Y, feature_scaler, target_scaler, config):
    """
    Scale input features and targets using pre-fitted scalers.

    Args:
        X: Input data (samples, seq_len, nodes, features)
        Y: Target data (samples, horizon, nodes)
        feature_scaler: Pre-fitted scaler for features
        target_scaler: Pre-fitted scaler for targets
        config: Configuration dict

    Returns:
        X_scaled, Y_scaled: Scaled arrays
    """
    n_samples, seq_len, n_nodes, n_features = X.shape
    wind_start_idx = config.get('wind_dir_start_idx', 17)

    # Apply log1p to skewed input features — must match fit_scalers_on_train.
    if config.get('use_log_transform', False):
        X_to_scale = X.copy()
        for idx in config.get('log_transform_indices', [0]):
            X_to_scale[:, :, :, idx] = np.log1p(X[:, :, :, idx])
        Y_to_scale = np.log1p(Y)
    else:
        X_to_scale = X
        Y_to_scale = Y

    # Scale features
    X_flat = X_to_scale.reshape(-1, n_features)
    X_scaled_features = feature_scaler.transform(X_flat[:, :wind_start_idx])

    # Reconstruct X with scaled features + unscaled wind one-hot
    X_scaled_flat = np.concatenate([
        X_scaled_features,
        X_flat[:, wind_start_idx:]  # Wind one-hot stays unchanged
    ], axis=1)
    X_scaled = X_scaled_flat.reshape(n_samples, seq_len, n_nodes, n_features)

    # Scale targets — per-station or global
    if isinstance(target_scaler, list):
        n_s, h_s, n_n = Y_to_scale.shape
        Y_scaled = np.zeros_like(Y_to_scale)
        for s in range(n_n):
            Y_scaled[:, :, s] = target_scaler[s].transform(
                Y_to_scale[:, :, s].reshape(-1, 1)
            ).reshape(n_s, h_s)
    else:
        Y_flat = Y_to_scale.reshape(-1, 1)
        Y_scaled = target_scaler.transform(Y_flat).reshape(Y.shape)

    return X_scaled.astype(np.float32), Y_scaled.astype(np.float32)


def scale_future_met(Z, feature_scaler, config):
    """
    Scale future meteorological features using the training-fitted feature scaler.

    Z contains: temp(6), pres(7), dewp(8), rain(9), wspm(10) + wind direction one-hot (17-32).
    The first 5 features (indices 0-4 within Z) correspond to original feature indices 6-10,
    which are columns 6-10 in the feature_scaler (fitted on original features 0-16).
    Wind direction (indices 5-20 within Z) is one-hot — no scaling needed.
    """
    n_samples, h, n_nodes, f_met = Z.shape
    Z_flat = Z.reshape(-1, f_met)

    # Reconstruct a dummy array matching the feature_scaler's input shape (17 features: 0-16)
    # Place the 5 met features at their original positions (columns 6-10)
    n_scaler_cols = feature_scaler.n_features_in_   # 17
    dummy = np.zeros((len(Z_flat), n_scaler_cols), dtype=np.float32)
    dummy[:, 6:11] = Z_flat[:, :5]                  # temp, pres, dewp, rain, wspm
    dummy_scaled = feature_scaler.transform(dummy)

    # Reconstruct scaled Z: scaled met features + unchanged wind direction one-hot
    Z_scaled_flat = np.concatenate([dummy_scaled[:, 6:11], Z_flat[:, 5:]], axis=1)
    return Z_scaled_flat.reshape(n_samples, h, n_nodes, f_met).astype(np.float32)


def create_dataloaders(train_data, val_data, test_data, config):
    """Create PyTorch DataLoaders."""
    X_train, Y_train = train_data[0], train_data[1]
    X_val,   Y_val   = val_data[0],   val_data[1]
    X_test,  Y_test  = test_data[0],  test_data[1]
    Z_train = train_data[2] if len(train_data) > 2 else None
    Z_val   = val_data[2]   if len(val_data)   > 2 else None
    Z_test  = test_data[2]  if len(test_data)  > 2 else None

    # Convert to tensors — include Z if future_met is enabled
    def _make_dataset(X, Y, Z):
        tensors = [torch.FloatTensor(X), torch.FloatTensor(Y)]
        if Z is not None:
            tensors.append(torch.FloatTensor(Z))
        return TensorDataset(*tensors)

    train_dataset = _make_dataset(X_train, Y_train, Z_train)
    val_dataset   = _make_dataset(X_val,   Y_val,   Z_val)
    test_dataset  = _make_dataset(X_test,  Y_test,  Z_test)
    
    train_loader = DataLoader(
        train_dataset,
        batch_size=config['batch_size'],
        shuffle=True,
        drop_last=True
    )
    val_loader = DataLoader(
        val_dataset,
        batch_size=config['batch_size'],
        shuffle=False
    )
    test_loader = DataLoader(
        test_dataset,
        batch_size=config['batch_size'],
        shuffle=False
    )
    
    return train_loader, val_loader, test_loader


# ============================================================================
# Training Functions
# ============================================================================

def pretrain_met_forecaster(met_forecaster, X_train_scaled, Z_train_scaled,
                             X_val_scaled, Z_val_scaled, config, device):
    """
    Pre-train MeteorologicalForecaster on (X_met, Z_met) with MSE loss.

    Uses the dynamic wind-aware adjacency (built from full scaled X) so the GAT
    sees the same graph structure it will encounter during PM2.5 training.
    Returns the trained forecaster in eval mode with best-val-loss weights restored.
    """
    met_cols  = config['future_met_indices']          # [6,7,8,9,10,17,...,32]
    n_epochs  = config.get('met_pretrain_epochs', 25)
    patience  = config.get('met_pretrain_patience', 5)
    bs        = config['batch_size']
    use_wind  = config.get('use_wind_adjacency', False)

    # Build pre-training DataLoaders: full X (for adj) + X_met (model input) + Z (target)
    def _make_met_ds(X_full, Z):
        return TensorDataset(
            torch.FloatTensor(X_full),
            torch.FloatTensor(X_full[:, :, :, met_cols]),  # X_met subset
            torch.FloatTensor(Z),
        )

    tr_loader = DataLoader(_make_met_ds(X_train_scaled, Z_train_scaled),
                           batch_size=bs, shuffle=True, drop_last=True)
    va_loader = DataLoader(_make_met_ds(X_val_scaled, Z_val_scaled),
                           batch_size=bs, shuffle=False)

    optimizer = torch.optim.Adam(met_forecaster.parameters(), lr=1e-3)
    best_val  = float('inf')
    best_state = None
    stale      = 0

    print(f"\n  Pre-training MeteorologicalForecaster (up to {n_epochs} epochs, patience={patience})...")

    for epoch in range(n_epochs):
        # --- train ---
        met_forecaster.train()
        tr_loss = 0.0
        for X_full, X_met, Z_tgt in tr_loader:
            X_full = X_full.to(device)
            X_met  = X_met.to(device)
            Z_tgt  = Z_tgt.to(device)

            if use_wind:
                adj_b = build_dynamic_adjacency(X_full, config, device)
            else:
                adj_b = None  # not expected — use_wind_adjacency should always be True

            optimizer.zero_grad()
            Z_pred = met_forecaster(X_met, adj_b)
            loss   = F.mse_loss(Z_pred, Z_tgt)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(met_forecaster.parameters(), max_norm=1.0)
            optimizer.step()
            tr_loss += loss.item()

        # --- validate ---
        met_forecaster.eval()
        va_loss = 0.0
        with torch.no_grad():
            for X_full, X_met, Z_tgt in va_loader:
                X_full = X_full.to(device)
                X_met  = X_met.to(device)
                Z_tgt  = Z_tgt.to(device)
                if use_wind:
                    adj_b = build_dynamic_adjacency(X_full, config, device)
                Z_pred = met_forecaster(X_met, adj_b)
                va_loss += F.mse_loss(Z_pred, Z_tgt).item()

        tr_loss /= len(tr_loader)
        va_loss /= len(va_loader)
        print(f"    Epoch {epoch+1:3d}/{n_epochs} | Train MSE: {tr_loss:.6f} | Val MSE: {va_loss:.6f}")

        if va_loss < best_val:
            best_val   = va_loss
            best_state = {k: v.clone() for k, v in met_forecaster.state_dict().items()}
            stale      = 0
        else:
            stale += 1
            if stale >= patience:
                print(f"    Early stopping at epoch {epoch+1}.")
                break

    met_forecaster.load_state_dict(best_state)
    met_forecaster.eval()
    print(f"  Met forecaster ready. Best val MSE: {best_val:.6f}\n")
    return met_forecaster


def train_epoch(model, train_loader, optimizer, criterion, adj, config, teacher_forcing_ratio,
                met_forecaster=None):
    """Train for one epoch."""
    model.train()
    total_loss = 0
    device = config['device']
    use_wind_adj = config.get('use_wind_adjacency', False)
    met_cols = config.get('future_met_indices', [])

    for batch_idx, batch in enumerate(train_loader):
        X_batch = batch[0].to(device)
        Y_batch = batch[1].to(device)
        Z_batch = batch[2].to(device) if len(batch) > 2 else None

        # Gaussian noise augmentation: perturb continuous features only (not wind one-hot).
        # Applied in training only — validate() and compute_metrics() never call this path.
        if config.get('use_noise_augmentation', False):
            wind_start = config.get('wind_dir_start_idx', 17)
            X_batch = X_batch.clone()
            X_batch[:, :, :, :wind_start] += (
                torch.randn_like(X_batch[:, :, :, :wind_start]) * config.get('noise_std', 0.02)
            )

        optimizer.zero_grad()

        # Build dynamic adjacency if enabled
        if use_wind_adj:
            alpha_override = model.get_wind_alpha()
            static_adj_override = model.get_static_adj() if getattr(model, 'use_learnable_static_adj', False) else None
            adj_batch = build_dynamic_adjacency(X_batch, config, device, alpha_override=alpha_override,
                                               static_adj_override=static_adj_override)
        else:
            adj_batch = adj

        # Generate predicted future met via frozen MeteorologicalForecaster
        if met_forecaster is not None:
            with torch.no_grad():
                Z_batch = met_forecaster(X_batch[:, :, :, met_cols], adj_batch)
        elif config.get('met_forecast_mode') == 'persistence' and met_cols:
            last_met = X_batch[:, -1:, :, :][:, :, :, met_cols]  # (B, 1, N, F_met)
            Z_batch = last_met.expand(-1, config['horizon'], -1, -1).contiguous()

        # Forward pass
        predictions, _ = model(
            x=X_batch,
            adj=adj_batch,
            target=Y_batch,
            horizon=config['horizon'],
            teacher_forcing_ratio=teacher_forcing_ratio,
            future_met=Z_batch,
        )

        # predictions: (batch, horizon, num_nodes, 1)
        # Y_batch: (batch, horizon, num_nodes)
        predictions = predictions.squeeze(-1)

        # Persistence residual: model outputs delta from last observed PM2.5.
        # Add the baseline so loss is computed on final predictions vs actual targets.
        if config.get('use_persistence_residual', False):
            feat_idx = config.get('target_feature_idx', 0)
            y_last = X_batch[:, -1, :, feat_idx]           # (B, N) in global feature space
            if config.get('use_per_station_norm', False):
                # Convert: undo global feature standardization, apply per-station target standardization
                y_last = (y_last * config['_feat_pm25_scale'] + config['_feat_pm25_mean']
                          - config['_target_means']) / config['_target_scales']
            prior = y_last.unsqueeze(1).expand_as(predictions)  # (B, H, N)
            if config.get('use_horizon_residual_weights', False):
                hw = model.get_horizon_residual_weights().view(1, -1, 1)  # (1, H, 1)
                predictions = predictions + hw * prior
            else:
                predictions = predictions + prior

        # t-24 daily anchor: add learnable-gated PM2.5 from 24h ago.
        # y_{t-24} is the first timestep of the 24h lookback window (index 0).
        # Gradient flows through t24_alpha so the gate is optimized end-to-end.
        if config.get('use_t24_residual', False):
            feat_idx = config.get('target_feature_idx', 0)
            y_t24 = X_batch[:, 0, :, feat_idx]                        # (B, N)
            t24_alpha = model.get_t24_alpha()                          # scalar tensor
            predictions = predictions + t24_alpha * y_t24.unsqueeze(1).expand_as(predictions)

        # Compute loss
        loss = criterion(predictions, Y_batch)
        
        # Backward pass
        loss.backward()
        
        # Gradient clipping
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        
        optimizer.step()
        
        total_loss += loss.item()
    
    return total_loss / len(train_loader)


def validate(model, val_loader, criterion, adj, config, target_scaler=None, met_forecaster=None):
    """
    Validate model.

    Returns:
        val_loss: Mean EVT/MSE loss on normalized predictions (used for LR scheduler).
        val_mae:  Mean absolute error on original scale if target_scaler is provided,
                  otherwise on normalized scale. Used for early stopping and checkpoint
                  selection — decoupled from the loss function so EVT lambda changes
                  do not artificially trigger early stopping.
    """
    model.eval()
    total_loss = 0
    all_preds = []
    all_targets = []
    device = config['device']
    use_wind_adj = config.get('use_wind_adjacency', False)
    met_cols = config.get('future_met_indices', [])

    with torch.no_grad():
        for batch in val_loader:
            X_batch = batch[0].to(device)
            Y_batch = batch[1].to(device)
            Z_batch = batch[2].to(device) if len(batch) > 2 else None

            # Build dynamic adjacency if enabled
            if use_wind_adj:
                alpha_override = model.get_wind_alpha()
                static_adj_override = model.get_static_adj() if getattr(model, 'use_learnable_static_adj', False) else None
                adj_batch = build_dynamic_adjacency(X_batch, config, device, alpha_override=alpha_override,
                                                   static_adj_override=static_adj_override)
            else:
                adj_batch = adj

            # Generate predicted future met via frozen MeteorologicalForecaster
            if met_forecaster is not None:
                Z_batch = met_forecaster(X_batch[:, :, :, met_cols], adj_batch)
            elif config.get('met_forecast_mode') == 'persistence' and met_cols:
                last_met = X_batch[:, -1:, :, :][:, :, :, met_cols]  # (B, 1, N, F_met)
                Z_batch = last_met.expand(-1, config['horizon'], -1, -1).contiguous()

            # Forward pass (no teacher forcing)
            predictions, _ = model(
                x=X_batch,
                adj=adj_batch,
                target=None,
                horizon=config['horizon'],
                teacher_forcing_ratio=0.0,
                future_met=Z_batch,
            )

            predictions = predictions.squeeze(-1)

            # Persistence residual: add last observed PM2.5 to model delta output
            if config.get('use_persistence_residual', False):
                feat_idx = config.get('target_feature_idx', 0)
                y_last = X_batch[:, -1, :, feat_idx]
                if config.get('use_per_station_norm', False):
                    y_last = (y_last * config['_feat_pm25_scale'] + config['_feat_pm25_mean']
                              - config['_target_means']) / config['_target_scales']
                prior = y_last.unsqueeze(1).expand_as(predictions)
                if config.get('use_horizon_residual_weights', False):
                    hw = model.get_horizon_residual_weights().view(1, -1, 1)
                    predictions = predictions + hw * prior
                else:
                    predictions = predictions + prior

            # t-24 daily anchor
            if config.get('use_t24_residual', False):
                feat_idx = config.get('target_feature_idx', 0)
                y_t24 = X_batch[:, 0, :, feat_idx]
                t24_alpha = model.get_t24_alpha()
                predictions = predictions + t24_alpha * y_t24.unsqueeze(1).expand_as(predictions)

            loss = criterion(predictions, Y_batch)
            total_loss += loss.item()

            all_preds.append(predictions.cpu().numpy())
            all_targets.append(Y_batch.cpu().numpy())

    preds = np.concatenate(all_preds, axis=0)
    targets = np.concatenate(all_targets, axis=0)

    # Compute MAE in original scale for early stopping (loss-function-independent)
    if target_scaler is not None:
        preds_inv = inverse_transform_targets(preds, target_scaler)
        targets_inv = inverse_transform_targets(targets, target_scaler)
        if config.get('use_log_transform', False):
            preds_inv = np.expm1(preds_inv)
            targets_inv = np.expm1(targets_inv)
            preds_inv = np.clip(preds_inv, 0, None)
        val_mae = float(np.mean(np.abs(preds_inv - targets_inv)))
    else:
        val_mae = float(np.mean(np.abs(preds - targets)))

    return total_loss / len(val_loader), val_mae


def compute_metrics(model, test_loader, adj, config, target_scaler=None, met_forecaster=None):
    """Compute evaluation metrics on test set."""
    model.eval()
    device = config['device']
    use_wind_adj = config.get('use_wind_adjacency', False)
    met_cols = config.get('future_met_indices', [])

    all_preds = []
    all_targets = []

    use_residual = config.get('use_persistence_residual', False)
    use_t24 = config.get('use_t24_residual', False)
    feat_idx = config.get('target_feature_idx', 0)

    with torch.no_grad():
        for batch in test_loader:
            X_batch = batch[0].to(device)
            Y_batch = batch[1]
            Z_batch = batch[2].to(device) if len(batch) > 2 else None

            # Build dynamic adjacency if enabled
            if use_wind_adj:
                alpha_override = model.get_wind_alpha()
                static_adj_override = model.get_static_adj() if getattr(model, 'use_learnable_static_adj', False) else None
                adj_batch = build_dynamic_adjacency(X_batch, config, device, alpha_override=alpha_override,
                                                   static_adj_override=static_adj_override)
            else:
                adj_batch = adj

            # Generate predicted future met via frozen MeteorologicalForecaster
            if met_forecaster is not None:
                Z_batch = met_forecaster(X_batch[:, :, :, met_cols], adj_batch)
            elif config.get('met_forecast_mode') == 'persistence' and met_cols:
                last_met = X_batch[:, -1:, :, :][:, :, :, met_cols]  # (B, 1, N, F_met)
                Z_batch = last_met.expand(-1, config['horizon'], -1, -1).contiguous()

            predictions = model.predict(X_batch, adj_batch, horizon=config['horizon'],
                                        future_met=Z_batch)

            # Persistence residual: add last observed PM2.5 to model delta output
            if use_residual:
                y_last = X_batch[:, -1, :, feat_idx]                   # (B, N) in global feature space
                if config.get('use_per_station_norm', False):
                    y_last = (y_last * config['_feat_pm25_scale'] + config['_feat_pm25_mean']
                              - config['_target_means']) / config['_target_scales']
                prior = y_last.unsqueeze(1).expand_as(predictions)
                if config.get('use_horizon_residual_weights', False):
                    hw = model.get_horizon_residual_weights().view(1, -1, 1)
                    predictions = predictions + hw * prior
                else:
                    predictions = predictions + prior

            # t-24 daily anchor
            if use_t24:
                y_t24 = X_batch[:, 0, :, feat_idx]                     # (B, N)
                t24_alpha = model.get_t24_alpha()
                predictions = predictions + t24_alpha * y_t24.unsqueeze(1).expand_as(predictions)

            all_preds.append(predictions.cpu().numpy())
            all_targets.append(Y_batch.numpy())
    
    preds = np.concatenate(all_preds, axis=0)
    targets = np.concatenate(all_targets, axis=0)
    
    # Inverse transform if scaler provided
    if target_scaler is not None:
        preds = inverse_transform_targets(preds, target_scaler)
        targets = inverse_transform_targets(targets, target_scaler)
        if config.get('use_log_transform', False):
            preds = np.expm1(preds)
            targets = np.expm1(targets)
            preds = np.clip(preds, 0, None)

    # Compute metrics
    mse = np.mean((preds - targets) ** 2)
    rmse = np.sqrt(mse)
    mae = np.mean(np.abs(preds - targets))
    
    # MAPE (use threshold to avoid division by small values)
    # PM2.5 values below 5 µg/m³ are very low and can cause unstable MAPE
    mape_threshold = 5.0
    mask = targets > mape_threshold
    if mask.any():
        mape = np.mean(np.abs((preds[mask] - targets[mask]) / targets[mask])) * 100
    else:
        mape = float('nan')

    return {
        'MSE': mse,
        'RMSE': rmse,
        'MAE': mae,
        'MAPE': mape
    }


# ============================================================================
# Main Training Loop
# ============================================================================

def train(config, trial=None):
    """Main training function."""
    print("=" * 60)
    print("GCN-LSTM Training")
    print("=" * 60)

    if config.get('seed') is not None:
        set_global_seed(config['seed'], deterministic=config.get('deterministic', False))
        print(f"Seed: {config['seed']} (deterministic={config.get('deterministic', False)})")

    device = config['device']
    print(f"\nDevice: {device}")

    # Load data
    print("\n[1/6] Loading data...")
    X, Y, adj, Z = load_data(config)
    adj = torch.FloatTensor(adj).to(device)

    # Update config with actual dimensions
    config['input_dim'] = X.shape[-1]
    config['num_nodes'] = X.shape[2]

    # When an extra feature is inserted at index 17, wind one-hot shifts by one.
    if config.get('use_pm25_delta', False) or config.get('use_holiday_feature', False):
        config['wind_dir_start_idx'] = 18
        config['wind_dir_end_idx'] = 34

    # Split data BEFORE scaling to prevent data leakage
    print("\n[2/6] Splitting data...")
    train_data, val_data, test_data = split_data(X, Y, config)
    X_train, Y_train = train_data
    X_val, Y_val = val_data
    X_test, Y_test = test_data

    # Split Z along the same chronological boundaries if future_met is enabled
    if Z is not None:
        n = len(X)
        train_end = int(n * config['train_ratio'])
        val_end = int(n * (config['train_ratio'] + config['val_ratio']))
        Z_train, Z_val, Z_test = Z[:train_end], Z[train_end:val_end], Z[val_end:]
        print(f"  Z split: train={len(Z_train)}, val={len(Z_val)}, test={len(Z_test)}")
    else:
        Z_train = Z_val = Z_test = None

    # Correlation-based static adjacency: computed from raw training PM2.5 (no leakage).
    # Replaces Gaussian distance decay as the static component; wind component unchanged.
    if config.get('use_correlation_adj', False):
        N = config['num_nodes']
        pm25_flat = X_train[:, :, :, 0].reshape(-1, N)          # (samples*seq_len, N)
        corr = np.corrcoef(pm25_flat.T).astype(np.float32)       # (N, N)
        corr = np.clip(corr, 0, None)                            # drop negative correlations
        row_sum = corr.sum(axis=1, keepdims=True)
        row_sum[row_sum == 0] = 1.0
        corr_norm = corr / row_sum                               # row-normalised
        config['_corr_adj'] = torch.FloatTensor(corr_norm).to(device)
        off_diag = (corr.sum() - np.trace(corr)) / (N * (N - 1))
        print(f"  Correlation adjacency built: mean off-diag={off_diag:.4f}  "
              f"range=[{corr.min():.3f}, {corr.max():.3f}]")

    # Fit scalers on training data only (prevents data leakage)
    print("\n[3/6] Fitting scalers on training data only...")
    feature_scaler, target_scaler, already_scaled = fit_scalers_on_train(X_train, Y_train, config)

    if already_scaled:
        # Data is already scaled, use as-is
        X_train_scaled, Y_train_scaled = X_train.astype(np.float32), Y_train.astype(np.float32)
        X_val_scaled, Y_val_scaled = X_val.astype(np.float32), Y_val.astype(np.float32)
        X_test_scaled, Y_test_scaled = X_test.astype(np.float32), Y_test.astype(np.float32)
        Z_train_scaled = Z_val_scaled = Z_test_scaled = None

        # Try to load existing target scaler for metrics inverse transform
        scaler_path = os.path.join(config['data_path'], 'target_scaler.save')
        if os.path.exists(scaler_path):
            target_scaler = joblib.load(scaler_path)
            print(f"  Loaded existing target scaler from {scaler_path}")
    else:
        # Scale all splits using training-fitted scalers
        X_train_scaled, Y_train_scaled = scale_data(X_train, Y_train, feature_scaler, target_scaler, config)
        X_val_scaled, Y_val_scaled = scale_data(X_val, Y_val, feature_scaler, target_scaler, config)
        X_test_scaled, Y_test_scaled = scale_data(X_test, Y_test, feature_scaler, target_scaler, config)

        # Scale future met features using the same training-fitted feature_scaler
        if Z_train is not None:
            Z_train_scaled = scale_future_met(Z_train, feature_scaler, config)
            Z_val_scaled   = scale_future_met(Z_val,   feature_scaler, config)
            Z_test_scaled  = scale_future_met(Z_test,  feature_scaler, config)
            print(f"  Z (future met) scaled: shape {Z_train_scaled.shape}, "
                  f"range [{Z_train_scaled[:,:,:,:5].min():.3f}, {Z_train_scaled[:,:,:,:5].max():.3f}] (met features)")
        else:
            Z_train_scaled = Z_val_scaled = Z_test_scaled = None

        print(f"  Feature scaler mean[:3]: {feature_scaler.mean_[:3]}  std[:3]: {feature_scaler.scale_[:3]}")
        if isinstance(target_scaler, list):
            means = [sc.mean_[0] for sc in target_scaler]
            stds  = [sc.scale_[0] for sc in target_scaler]
            print(f"  Target scalers (per-station): mean [{min(means):.4f}, {max(means):.4f}]  "
                  f"std [{min(stds):.4f}, {max(stds):.4f}]")
        else:
            print(f"  Target scaler mean: {target_scaler.mean_[0]:.4f}  std: {target_scaler.scale_[0]:.4f}")

        # Save scalers for inference
        os.makedirs(config['data_path'], exist_ok=True)
        joblib.dump(target_scaler, os.path.join(config['data_path'], 'target_scaler.save'))
        joblib.dump(feature_scaler, os.path.join(config['data_path'], 'feature_scaler.save'))

        # Pre-compute residual conversion tensors for per-station norm (used in train/val/test loops)
        if config.get('use_per_station_norm', False):
            config['_feat_pm25_mean']  = torch.tensor(float(feature_scaler.mean_[0]),  dtype=torch.float32, device=device)
            config['_feat_pm25_scale'] = torch.tensor(float(feature_scaler.scale_[0]), dtype=torch.float32, device=device)
            config['_target_means']  = torch.tensor([sc.mean_[0]  for sc in target_scaler], dtype=torch.float32, device=device)
            config['_target_scales'] = torch.tensor([sc.scale_[0] for sc in target_scaler], dtype=torch.float32, device=device)

    # Derive EVT threshold from SCALED training targets to match loss computation
    if config.get('evt_threshold') is None:
        q = config['evt_tail_quantile']
        mode = config.get('evt_threshold_mode', 'global')
        if mode == 'global':
            config['evt_threshold'] = float(np.quantile(Y_train_scaled, q))
        elif mode == 'per_node':
            # Y_train_scaled: (samples, horizon, nodes) -> per-node threshold over (samples, horizon)
            config['evt_threshold'] = np.quantile(Y_train_scaled, q, axis=(0, 1)).astype(np.float32)
        else:
            raise ValueError(f"Unknown evt_threshold_mode: {mode}")

    # When using predicted met: pre-train MeteorologicalForecaster on oracle Z,
    # then pass it as a frozen Z-generator during PM2.5 training.
    # Z is excluded from the PM2.5 DataLoader — the forecaster generates it per batch.
    met_forecaster = None
    if config.get('met_forecast_mode') == 'predicted':
        if Z_train_scaled is None:
            raise ValueError(
                "met_forecast_mode='predicted' requires Z (future met oracle) for pre-training. "
                "Set use_future_met=True and generate Z_24.npy first."
            )
        met_forecaster = MeteorologicalForecaster(
            met_dim=len(config['future_met_indices']),
            hidden_dim=config.get('met_hidden_dim', 64),
            num_nodes=config['num_nodes'],
            horizon=config['horizon'],
            num_tf_layers=config.get('met_tf_layers', 2),
            num_heads=config.get('met_num_heads', 4),
            dropout=config['dropout'],
            gat_version=config.get('gat_version', 'v1'),
        ).to(device)
        met_forecaster = pretrain_met_forecaster(
            met_forecaster,
            X_train_scaled, Z_train_scaled,
            X_val_scaled,   Z_val_scaled,
            config, device,
        )
        # Met forecaster is now frozen — PM2.5 DataLoader carries no Z
        Z_dl_train = Z_dl_val = Z_dl_test = None
    elif config.get('met_forecast_mode') == 'persistence':
        # Persistence generates Z from X per batch — no need to carry oracle Z in DataLoader
        Z_dl_train = Z_dl_val = Z_dl_test = None
    else:
        Z_dl_train, Z_dl_val, Z_dl_test = Z_train_scaled, Z_val_scaled, Z_test_scaled

    # Create dataloaders with scaled data (Z included when future_met is enabled and not predicted)
    train_loader, val_loader, test_loader = create_dataloaders(
        (X_train_scaled, Y_train_scaled, Z_dl_train),
        (X_val_scaled,   Y_val_scaled,   Z_dl_val),
        (X_test_scaled,  Y_test_scaled,  Z_dl_test),
        config
    )

    # Create model
    print("\n[4/6] Creating model...")
    model_type = config.get('model_type', 'gcn_lstm')
    future_met_dim = len(config['future_met_indices']) if config.get('use_future_met') else 0
    if model_type == 'graph_transformer':
        model = GraphTransformerModel(
            input_dim=config['input_dim'],
            hidden_dim=config['hidden_dim'],
            output_dim=config['output_dim'],
            num_nodes=config['num_nodes'],
            num_tf_layers=config.get('num_tf_layers', 2),
            num_heads=config['num_heads'],
            dropout=config['dropout'],
            horizon=config['horizon'],
            use_node_embeddings=config.get('use_node_embeddings', True),
            use_learnable_alpha_gate=config.get('use_learnable_alpha_gate', False),
            initial_wind_alpha=config.get('wind_alpha', 0.6),
            graph_conv=config.get('graph_conv', 'gcn'),
            num_gat_layers=config.get('num_gat_layers', 1),
            gat_version=config.get('gat_version', 'v1'),
            use_post_temporal_gat=config.get('use_post_temporal_gat', False),
            use_temporal_attention_head=config.get('use_temporal_attention_head', False),
            use_t24_residual=config.get('use_t24_residual', False),
            initial_t24_alpha=config.get('initial_t24_alpha', 0.3),
            future_met_dim=future_met_dim,
            use_multiscale_temporal=config.get('use_multiscale_temporal', False),
            local_window=config.get('local_window', 6),
            n_local_layers=config.get('n_local_layers', 1),
            use_horizon_residual_weights=config.get('use_horizon_residual_weights', False),
            use_learnable_static_adj=config.get('use_learnable_static_adj', False),
            initial_distance_sigma=config.get('distance_sigma', 1800.0),
        ).to(device)
        print(f"  Model type: GraphTransformerModel  graph_conv={config.get('graph_conv', 'gcn')}  gat_version={config.get('gat_version', 'v1')}  num_gat_layers={config.get('num_gat_layers', 1)}  post_gat={config.get('use_post_temporal_gat', False)}  temporal_attn_head={config.get('use_temporal_attention_head', False)}")
    else:
        model = GCNLSTMModel(
            input_dim=config['input_dim'],
            hidden_dim=config['hidden_dim'],
            output_dim=config['output_dim'],
            num_nodes=config['num_nodes'],
            num_layers=config['num_layers'],
            num_heads=config['num_heads'],
            dropout=config['dropout'],
            horizon=config['horizon'],
            use_direct_decoding=config.get('use_direct_decoding', False),
            use_learnable_alpha_gate=config.get('use_learnable_alpha_gate', False),
            initial_wind_alpha=config.get('wind_alpha', 0.6),
            graph_conv=config.get('graph_conv', 'gcn'),
        ).to(device)
        print(f"  Model type: GCNLSTMModel  graph_conv={config.get('graph_conv', 'gcn')}")

    print(f"  Model parameters: {model.get_num_params():,}")
    if config.get('use_wind_adjacency', False) and config.get('use_learnable_alpha_gate', False):
        print(f"  Learnable Alpha Gate: ON (initial alpha={config.get('wind_alpha', 0.6):.3f})")
    
    # Loss and optimizer
    if config.get('loss_type', 'mse') == 'evt_hybrid':
        # Determine initial lambda (may be adjusted by schedule)
        if config.get('evt_use_lambda_schedule', False):
            initial_lambda = config['evt_lambda_schedule']['initial']
        else:
            initial_lambda = config['evt_lambda']

        criterion = EVTHybridLoss(
            threshold=config['evt_threshold'],
            lambda_tail=initial_lambda,
            xi=config['evt_xi'],
            asymmetric_penalty=config.get('evt_asymmetric_penalty', False),
            under_penalty_multiplier=config.get('evt_under_penalty_multiplier', 2.0),
            horizon_weights=config.get('horizon_loss_weights', None),
        )

        # Print configuration
        thr = config['evt_threshold']
        if isinstance(thr, (list, tuple, np.ndarray)):
            thr_mean = float(np.mean(thr))
            thr_str = f"per_node(mean={thr_mean:.4f})"
        else:
            thr_str = f"{float(thr):.4f}"
        print(
            f"  Loss: EVT Hybrid (lambda={initial_lambda}, "
            f"q={config['evt_tail_quantile']}, xi={config['evt_xi']}, "
            f"threshold={thr_str})"
        )
        hw = config.get('horizon_loss_weights', None)
        if hw is not None:
            import numpy as _np
            hw_arr = _np.array(hw, dtype=float)
            hw_norm = hw_arr / hw_arr.mean()
            print(f"  Horizon weights (normalized): {[round(w, 3) for w in hw_norm.tolist()]}")

        if config.get('evt_asymmetric_penalty', False):
            print(
                f"  Asymmetric Penalty: ON (under-prediction multiplier={config.get('evt_under_penalty_multiplier', 2.0)}x)"
            )

        if config.get('evt_use_lambda_schedule', False):
            sched = config['evt_lambda_schedule']
            print(
                f"  Adaptive Lambda Schedule: {sched['initial']} -> {sched['mid']} -> {sched['final']} "
                f"(warmup={sched['warmup_epochs']}, mid={sched['mid_epochs']}, {sched['transition']})"
            )
    else:
        criterion = nn.MSELoss()
        print("  Loss: MSE")

    optimizer = optim.Adam(
        model.parameters(),
        lr=config['learning_rate'],
        weight_decay=config['weight_decay']
    )
    
    # Learning rate scheduler: cosine annealing with linear warmup, or ReduceLROnPlateau
    if config.get('use_cosine_schedule', False):
        warmup = config.get('cosine_warmup_epochs', 5)
        total  = config['epochs']
        eta_min_ratio = config.get('cosine_min_lr_ratio', 0.05)
        def _cosine_lr_lambda(epoch):
            if epoch < warmup:
                return float(epoch + 1) / warmup
            progress = (epoch - warmup) / max(total - warmup, 1)
            return eta_min_ratio + (1.0 - eta_min_ratio) * 0.5 * (1.0 + math.cos(math.pi * progress))
        scheduler = optim.lr_scheduler.LambdaLR(optimizer, lr_lambda=_cosine_lr_lambda)
    else:
        scheduler = optim.lr_scheduler.ReduceLROnPlateau(
            optimizer, mode='min', factor=0.5, patience=5
        )
    
    # Training loop
    print("\n[5/6] Training...")
    print("-" * 60)
    
    best_val_loss = float('inf')   # used only for LR scheduler
    best_val_mae = float('inf')    # used for early stopping and checkpoint selection
    patience_counter = 0
    history = {'train_loss': [], 'val_loss': [], 'val_mae': []}
    start_epoch = 0
    
    save_checkpoints = config.get('save_checkpoints', True)
    evaluate_test = config.get('evaluate_test', True)
    save_history = config.get('save_history', True)
    best_state_dict = None

    # Create checkpoint directory if needed
    if save_checkpoints:
        os.makedirs(config['model_save_path'], exist_ok=True)

    # Determine checkpoint filename
    if config.get('use_versioned_checkpoint', False):
        arch_name = config.get('architecture_name', 'model')
        hw_tag = config.get('hardware_tag', 'unknown')
        checkpoint_filename = f"{arch_name}_{hw_tag}_best.pt"
    else:
        checkpoint_filename = config['best_model_name']

    checkpoint_path = os.path.join(config['model_save_path'], checkpoint_filename)
    if save_checkpoints:
        print(f"\nCheckpoint path: {checkpoint_path}")
    else:
        print(f"\nCheckpoint path: {checkpoint_path} (disabled during this run)")

    # Resume from checkpoint if specified
    if save_checkpoints and config.get('resume', False) and os.path.exists(checkpoint_path):
        print(f"\nResuming from checkpoint: {checkpoint_path}")
        checkpoint = torch.load(checkpoint_path, weights_only=False)
        model.load_state_dict(checkpoint['model_state_dict'])
        optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
        start_epoch = checkpoint['epoch'] + 1
        best_val_loss = checkpoint['val_loss']
        best_val_mae = checkpoint.get('val_mae', float('inf'))
        print(f"  Resuming from epoch {start_epoch}")
        print(f"  Best val_loss: {best_val_loss:.6f}, best val_mae: {best_val_mae:.4f}")
    
    for epoch in range(start_epoch, config['epochs']):
        start_time = time.time()

        # Update EVT lambda if using adaptive schedule
        if config.get('loss_type', 'mse') == 'evt_hybrid' and config.get('evt_use_lambda_schedule', False):
            new_lambda = get_evt_lambda_for_epoch(
                epoch,
                config['evt_lambda_schedule'],
                config['epochs']
            )
            criterion.set_lambda(new_lambda)

            # Log lambda changes (only when it actually changes)
            if epoch == 0 or epoch == config['evt_lambda_schedule'].get('warmup_epochs', 20) or \
               epoch == config['evt_lambda_schedule'].get('mid_epochs', 40):
                print(f"  -> EVT lambda updated to {new_lambda:.4f} at epoch {epoch+1}")

        # Calculate teacher forcing ratio (linear decay)
        tf_ratio = config['teacher_forcing_start'] - \
                   (config['teacher_forcing_start'] - config['teacher_forcing_end']) * \
                   (epoch / config['epochs'])

        # Train
        train_loss = train_epoch(
            model, train_loader, optimizer, criterion, adj, config, tf_ratio,
            met_forecaster=met_forecaster,
        )

        # Validate — get both loss (for LR scheduler) and MAE (for early stopping)
        val_loss, val_mae = validate(model, val_loader, criterion, adj, config, target_scaler,
                                     met_forecaster=met_forecaster)

        # Step LR scheduler — cosine uses epoch count, ReduceLROnPlateau uses val_mae.
        if config.get('use_cosine_schedule', False):
            scheduler.step()
        else:
            scheduler.step(val_mae)

        # Record history
        history['train_loss'].append(train_loss)
        history['val_loss'].append(val_loss)
        history['val_mae'].append(val_mae)

        elapsed = time.time() - start_time
        alpha_str = ""
        if config.get('use_wind_adjacency', False) and config.get('use_learnable_alpha_gate', False):
            alpha_str = f"Alpha: {float(model.get_wind_alpha().detach().cpu()):.3f} | "
        if config.get('use_t24_residual', False):
            alpha_str += f"T24: {float(model.get_t24_alpha().detach().cpu()):.3f} | "

        # Display current lambda if using schedule
        lambda_str = ""
        if config.get('loss_type', 'mse') == 'evt_hybrid' and config.get('evt_use_lambda_schedule', False):
            lambda_str = f"λ: {criterion.lambda_tail:.3f} | "

        scale_label = "µg/m³" if target_scaler is not None else "norm"
        print(f"Epoch {epoch+1:3d}/{config['epochs']} | "
              f"Train Loss: {train_loss:.6f} | "
              f"Val Loss: {val_loss:.6f} | "
              f"Val MAE: {val_mae:.4f} ({scale_label}) | "
              f"{alpha_str}"
              f"{lambda_str}"
              f"TF: {tf_ratio:.2f} | "
              f"Time: {elapsed:.1f}s")

        # Early stopping and checkpoint selection: use val_mae (loss-function-independent)
        if val_mae < best_val_mae:
            best_val_mae = val_mae
            best_val_loss = val_loss
            patience_counter = 0

            # Keep best weights in memory (needed when checkpoint saving is disabled)
            best_state_dict = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}

            if save_checkpoints:
                # Save best model with metadata
                torch.save({
                    'epoch': epoch,
                    'model_state_dict': model.state_dict(),
                    'optimizer_state_dict': optimizer.state_dict(),
                    'val_loss': val_loss,
                    'val_mae': val_mae,
                    'train_loss': train_loss,
                    'config': config,
                    'hardware': {
                        'device': str(device),
                        'tag': config.get('hardware_tag', 'unknown'),
                        'cuda_available': torch.cuda.is_available(),
                        'cuda_device_name': torch.cuda.get_device_name(0) if torch.cuda.is_available() else None
                    },
                    'architecture': {
                        'name': config.get('architecture_name', 'unknown'),
                        'num_params': model.get_num_params(),
                        'use_direct_decoding': config.get('use_direct_decoding', False),
                        'use_wind_adjacency': config.get('use_wind_adjacency', False),
                        'use_learnable_alpha_gate': config.get('use_learnable_alpha_gate', False),
                        'learned_wind_alpha': (
                            float(model.get_wind_alpha().detach().cpu())
                            if model.get_wind_alpha() is not None else None
                        )
                    },
                    'timestamp': time.strftime('%Y-%m-%d %H:%M:%S')
                }, checkpoint_path)
                scale_label = "µg/m³" if target_scaler is not None else "norm"
                print(f"  -> Saved best model (val_mae: {val_mae:.4f} {scale_label})")
            else:
                scale_label = "µg/m³" if target_scaler is not None else "norm"
                print(f"  -> New best model in memory (val_mae: {val_mae:.4f} {scale_label})")
        else:
            patience_counter += 1
            if patience_counter >= config['patience']:
                print(f"\nEarly stopping at epoch {epoch+1}")
                break

        # Report intermediate value for Optuna and prune bad trials early
        # Use val_mae so pruning is loss-function-independent
        if trial is not None:
            trial.report(val_mae, step=epoch)
            if trial.should_prune():
                raise RuntimeError("TRIAL_PRUNED")
    
    # Restore best model weights
    if save_checkpoints and os.path.exists(checkpoint_path):
        checkpoint = torch.load(checkpoint_path, weights_only=False)
        model.load_state_dict(checkpoint['model_state_dict'])
    elif best_state_dict is not None:
        model.load_state_dict(best_state_dict)

    metrics = {'best_val_loss': best_val_loss, 'best_val_mae': best_val_mae}
    if evaluate_test:
        print("\n[6/6] Evaluating best model...")
        print("-" * 60)

        # Target scaler was already saved earlier and is in scope
        test_metrics = compute_metrics(model, test_loader, adj, config, target_scaler,
                                       met_forecaster=met_forecaster)
        metrics.update(test_metrics)

        print("\nTest Set Metrics:")
        for name, value in test_metrics.items():
            print(f"  {name}: {value:.4f}")
    else:
        print("\n[6/6] Skipping test evaluation (evaluate_test=False)")

    # Save training history
    if save_history:
        np.save(
            os.path.join(config['model_save_path'], 'history.npy'),
            history
        )
    
    print("\n" + "=" * 60)
    print("Training complete!")
    if save_checkpoints:
        print(f"Best model saved to: {checkpoint_path}")
    else:
        print("Best model checkpoint saving was disabled for this run.")
    print(f"Architecture: {config.get('architecture_name', 'N/A')}")
    print(f"Hardware: {config.get('hardware_tag', 'N/A')}")
    print("=" * 60)

    return model, history, metrics


if __name__ == "__main__":
    model, history, metrics = train(CONFIG)
